# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ispmail_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
